eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9070/eureka}
  instance:
    hostname: host.docker.internal
    preferIpAddress: true
    statusPageUrl: http://${eureka.instance.hostname}:${server.port}/status
spring:
  cloud:
    loadbalancer:
      health-check:
        interval: 10s
        refetch-instances-interval: 10s
