eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9070/eureka}
  instance:
    hostname: localhost
    preferIpAddress: true
