eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://host.docker.internal:9070/eureka}
  instance:
    hostname: host.docker.internal
    preferIpAddress: true
    statusPageUrl: http://${eureka.instance.hostname}:${server.port}/status
